<?php
$lyrics = $this->song->getLyrics();
?>

<ul data-role="listview">
<li>
    <img src="/images/album/list/<?php echo $this->song->getAlbum()->getId(); ?>.png" />
    <h3><?php echo $this->song->getTitle(); ?> (<?php echo $this->jukeboxTime($this->song->getDuration()); ?>)</h3>
    <p><?php echo $this->song->getArtist()->getName(); ?></p>
    <p><?php echo $current['song']['album']['name']; ?></p>
</li>
</ul>

<span style="clear: both; margin: 10px;"></span>

<?php if ($lyrics != '') : ?>
<div data-role="collapsible">
    <h3>Lyrics</h3>
    <p>
    <?php echo nl2br($lyrics); ?>
    </p>
</div>
<?php endif ?>

<form id="login" method="post" action="/mobile/song/queue/id/<?php echo $this->song->getId(); ?>/" data-ajax="false">
    <input type="submit" data-theme="c" value="Add song to queue" />
</form>

<span style="clear: both; margin: 10px;"></span>

<ul data-role="listview">
    <li data-role="list-divider">Album</li>
    <li>
        <a href="/mobile/album/detail/id/<?php echo $this->song->getAlbum()->getId(); ?>/">
        <img src="/images/album/list/<?php echo $this->song->getAlbum()->getId(); ?>.png" />
        <h3><?php echo $this->song->getAlbum()->getName(); ?></h3>
        <p><?php echo count($this->song->getAlbum()->getSongs()) ?> songs</p>
        </a>
    </li>
    <li data-role="list-divider">Artist</li>
    <li>
        <a href="/mobile/artist/detail/id/<?php echo $this->song->getArtist()->getId(); ?>/">
        <img src="/images/artist/list/<?php echo $this->song->getArtist()->getId(); ?>.png" />
        <h3><?php echo $this->song->getArtist()->getName(); ?></h3>
            <p><?php echo count($this->song->getArtist()->getAlbums()) ?> albums</p>
        </a>
    </li>
</ul>

