<?php
$auth = Zend_Auth::getInstance();
?>
!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php
    # Title
    echo $this->headTitle();

    # Meta data
    echo $this->headMeta();

    # CSS
    echo $this->headLink()
        ->appendStylesheet($this->baseUrl() . '/css/jquery.mobile-1.1.0.min.css');

    # Javascript
    echo $this->headScript()
        ->appendFile($this->baseUrl() . '/js/jquery-1.7.2.min.js', 'text/javascript')
        ->appendFile($this->baseUrl() . '/js/jquery.mobile-1.1.0.min.js', 'text/javascript')
        ->appendFile($this->baseUrl() . '/js/custom-mobile.js', 'text/javascript');
    ?>
</head>
<body>
<body>
<!-- Home -->
<div data-role="page" id="wjbpage">
    <div data-theme="a" data-role="header">
<?php if ($auth->hasIdentity()) : ?>
        <?php if (Zend_Controller_Front::getInstance()->getRequest()->getControllerName() == 'index') : ?>
            <a href="/mobile/auth/logout/" data-icon="home" class="ui-btn-left" rel="external">Logout</a>
        <?php else: ?>
            <a href="/mobile/" data-icon="home" class="ui-btn-left" rel="external">Home</a>
        <?php endif ?>
<?php endif ?>
        <h3>
            <?php echo $this->headerString ?>
        </h3>
<?php if ($auth->hasIdentity()) : ?>
        <a href="javascript:;" data-icon="search" class="ui-btn-right" onclick="toggleSearchBox()">Search</a>
<?php endif ?>
    </div>
    <div data-role="content" style="padding: 15px">
<?php if ($auth->hasIdentity()) : ?>
        <form id="searchForm" method="post" action="/mobile/search/" data-ajax="false" <?php if (!isset($this->searchQuery)): ?>style="display: none"<?php endif ?>>
            <div data-role="fieldcontain" class="ui-hide-label">
                <input id="fQuery" name="q" value="<?php echo $this->searchQuery ?>" type="search" placeholder="Search" data-mini="true" />
            </div>
</form>
<?php endif ?>

            <?php echo $this->layout()->content; ?>
    </div>
    <div data-theme="a" data-role="footer" data-position="fixed">
        <h3>
            The Wicked Net
        </h3>
    </div>
</div>

<script>
    $(document).bind("mobileinit", function(){
        $.extend(  $.mobile , {
            ajaxFormsEnabled: false
        });
    });
</script>
</body>
</html>




