[tool.black]
line-length = 80
skip-string-normalization = true

[tool.coverage.run]
omit = [
    # omit external code which we have no control over
    "wickedjukebox/remotes/*",
]

[tool.isort]
profile = "black"
line_length = 80
