[tool.black]
line-length = 80

[tool.coverage.run]
branch = true
dynamic_context = "test_function"
omit = [
    # omit external code which we have no control over
    "wickedjukebox/remotes/*",
]

[tool.isort]
profile = "black"
line_length = 80

[tool.coverage.report]
sort = "-cover"
show_missing = true
skip_covered = true

[tool.coverage.html]
show_contexts = true
