metadata = None

from sqlalchemy import (
    Column,
    DateTime,
    ForeignKey,
    Integer,
    String,
    Table,
    Unicode,
    func,
)

from sqlalchemy.dialects.mysql import (
    BIGINT,
    DATE,
    DATETIME,
    DOUBLE,
    ENUM,
    FLOAT,
    INTEGER,
    LONGTEXT,
    TEXT,
    TIMESTAMP,
    TINYINT,
    VARCHAR,
)


Table('setting_text',
      metadata,
      Column(u'var', VARCHAR(length=32, charset=u'latin1'),
             primary_key=True, nullable=False),
      Column(u'text_en', TEXT(charset=u'latin1'),
             nullable=False),
      Column('comment', Unicode()), schema=None)

Table('setting',
      metadata,
      Column(u'var', VARCHAR(collation=u'utf8_unicode_ci', length=32),
             primary_key=True, nullable=False),
      Column('value', Unicode()),
      Column(u'channel_id',
             INTEGER(display_width=10),
             primary_key=True,
             nullable=False,
             server_default=0),
      Column(u'user_id', INTEGER(display_width=10),
             primary_key=True, nullable=False,
             server_default=0), schema=None)

Table('dynamicPlaylist',
      metadata,
      Column(u'id', INTEGER(display_width=10),
             primary_key=True, nullable=False),
      Column(u'channel_id',
             INTEGER(display_width=11)),
      Column(u'group_id', INTEGER(display_width=11),
             nullable=False),
      Column(u'probability', FLOAT(),
             nullable=False),
      Column('label', Unicode(length=64)),
      Column('query', Unicode()), schema=None)

Table('shoutbox',
      metadata,
      Column('message', Unicode(length=255)), schema=None)

Table('state',
      metadata,
      Column(u'channel_id', INTEGER(display_width=10),
             primary_key=True, nullable=False),
      Column(u'state',
             VARCHAR(length=64,
                     charset=u'utf8'),
             primary_key=True,
             nullable=False),
      Column(u'value', VARCHAR(length=255, charset=u'utf8')),
      schema=None)

Table(u'groups',
      metadata,
      Column(u'id', INTEGER(display_width=10),
             primary_key=True, nullable=False),
      Column(u'title',
             VARCHAR(collation=u'utf8_unicode_ci',
                     length=32),
             nullable=False),
      Column(u'admin', INTEGER(display_width=1),
             nullable=False,
             server_default=0),
      Column(u'nocredits', INTEGER(display_width=11),
             nullable=False,
             server_default=0),
      Column(u'queue_skip', INTEGER(display_width=11),
             nullable=False,
             server_default=0),
      Column(u'queue_remove', INTEGER(display_width=11),
             nullable=False,
             server_default=0),
      Column(u'queue_add', INTEGER(display_width=11),
             nullable=False,
             server_default=0), schema=None)

Table('artist',
      metadata,
      Column(u'id', INTEGER(display_width=10),
             primary_key=True, nullable=False),
      Column('name',
             Unicode(length=128)),
      Column(u'country', VARCHAR(collation=u'utf8_unicode_ci', length=16)),
      Column(u'summary',
             TEXT(collation=u'utf8_unicode_ci'),
             ),
      Column(u'bio',
             LONGTEXT(collation=u'utf8_unicode_ci')),
      Column(u'website', VARCHAR(collation=u'utf8_unicode_ci', length=255)),
      Column(u'wikipage',
             VARCHAR(collation=u'utf8_unicode_ci',
                     length=255)),
      Column(u'lastfm_mbid', VARCHAR(collation=u'utf8_unicode_ci', length=64)),
      Column('added', DateTime(),
             nullable=False,
             default=func.now()),
      schema=None)

Table('tag',
      metadata,
      Column(u'label', VARCHAR(collation=u'utf8_unicode_ci', length=32),
             primary_key=True, nullable=False),
      Column(u'inserted', TIMESTAMP(), nullable=False,
             server_default=func.now()),
      Column(u'modified', TIMESTAMP(), nullable=True,
             server_default=None), schema=None)

Table('channel',
      metadata,
      Column(u'id', INTEGER(display_width=10),
             primary_key=True, nullable=False),
      Column('name',
             Unicode(length=32)),
      Column(u'public', TINYINT(display_width=1),
             nullable=False,
             server_default=1),
      Column('backend',
             Unicode(length=64)),
      Column('backend_params', Unicode()),
      Column(u'ping', DATETIME()),
      Column(u'active', TINYINT(display_width=1),
             nullable=False,
             server_default=0),
      Column(u'status',
             INTEGER(display_width=11)),
      schema=None)

Table(u'genre',
      metadata,
      Column(u'id', INTEGER(display_width=10), primary_key=True,
             nullable=False),
      Column(u'name',
             VARCHAR(collation=u'utf8_unicode_ci',
                     length=128)),
      Column('added', DateTime(), nullable=False,
             default=func.now()),
      schema=None)

Table(u'users',
      metadata,
      Column(u'id', INTEGER(display_width=10), primary_key=True,
             nullable=False),
      Column(u'username',
             VARCHAR(collation=u'utf8_unicode_ci',
                     length=32),
             nullable=False),
      Column(u'cookie',
             VARCHAR(collation=u'utf8_unicode_ci',
                     length=32),
             nullable=False),
      Column(u'password', VARCHAR(collation=u'utf8_unicode_ci', length=32),
             nullable=False),
      Column(u'fullname',
             VARCHAR(collation=u'utf8_unicode_ci',
                     length=64),
             nullable=False),
      Column(u'email', VARCHAR(collation=u'utf8_unicode_ci', length=128),
             nullable=False),
      Column(u'credits',
             INTEGER(display_width=5),
             nullable=False),
      Column(u'group_id', INTEGER(display_width=10), ForeignKey(u'groups.id'),
             nullable=False),
      Column(u'downloads',
             INTEGER(display_width=10),
             nullable=False,
             server_default=0),
      Column(u'votes', INTEGER(display_width=10),
             nullable=False,
             server_default=0),
      Column(u'skips',
             INTEGER(display_width=10),
             nullable=False,
             server_default=0),
      Column(u'selects', INTEGER(display_width=10),
             nullable=False,
             server_default=0),
      Column('added',
             DateTime(),
             nullable=False,
             default=func.now()),
      Column(u'proof_of_life', DATETIME(), nullable=False),
      Column(u'proof_of_listening', DATETIME()),
      Column(u'IP',
             VARCHAR(collation=u'utf8_unicode_ci', length=32),
             nullable=False),
      Column(u'picture', VARCHAR(collation=u'utf8_unicode_ci', length=255),
             nullable=False),
      Column(u'lifetime',
             BIGINT(display_width=11),
             nullable=False),

      Column(u'channel_id', INTEGER(display_width=10), nullable=False,
             server_default=1),
      schema=None)

Table('album',
      metadata,
      Column(u'id', INTEGER(display_width=10), primary_key=True,
             nullable=False),
      Column(u'artist_id', INTEGER(display_width=10),
             ForeignKey(u'artist.id'),
             nullable=False),
      Column('name',
             Unicode(length=128)),
      Column(u'release_date', DATE()),
      Column('added',
             DateTime(),
             nullable=False,
             default=func.now()),
      Column(u'downloaded', INTEGER(display_width=10),
             nullable=False,
             server_default=0),
      Column('type',
             Unicode(length=32)),
      Column(u'path', VARCHAR(collation=u'utf8_unicode_ci', length=255),
             nullable=False), schema=None)

Table('song',
      metadata,
      Column(u'id', INTEGER(display_width=10), primary_key=True,
             nullable=False),
      Column(u'artist_id', INTEGER(display_width=10),
             ForeignKey(u'artist.id'),
             nullable=False),
      Column(u'album_id',
             INTEGER(display_width=10),
             ForeignKey(u'album.id')),
      Column(u'track_no', INTEGER(display_width=3)),
      Column('title', Unicode(length=128)),
      Column(u'duration',
             DOUBLE()),
      Column(u'year', INTEGER(display_width=4)),
      Column('localpath', Unicode(length=255)),
      Column(u'downloaded', INTEGER(display_width=10),
             server_default=0),
      Column(u'lastScanned', DATETIME()),
      Column(u'bitrate',
             INTEGER(display_width=5)),
      Column(u'filesize', INTEGER(display_width=32)),
      Column(u'checksum', VARCHAR(collation=u'utf8_unicode_ci', length=14)),
      Column('lyrics', Unicode()),
      Column(u'broken', TINYINT(display_width=1),
             server_default=0),
      Column(u'dirty',
             TINYINT(display_width=1),
             server_default=0),
      Column('added', DateTime(), nullable=False,
             default=func.now()),
      schema=None)

Table('user_song_standing',
      metadata,
      Column(u'user_id', INTEGER(display_width=10), ForeignKey(u'users.id'),
             primary_key=True, nullable=False),
      Column(u'song_id', INTEGER(display_width=11), ForeignKey(u'song.id'),
             primary_key=True, nullable=False),
      Column(u'standing', ENUM(u'love', u'hate'),
             nullable=False), schema=None)

Table('queue',
      metadata,
      Column(u'id', INTEGER(display_width=10), primary_key=True,
             nullable=False),
      Column(u'song_id', INTEGER(display_width=10),
             ForeignKey(u'song.id'),
             nullable=False),
      Column(u'user_id',
             INTEGER(display_width=10),
             ForeignKey(u'users.id')),
      Column(u'channel_id', INTEGER(display_width=10),
             ForeignKey(u'channel.id'), nullable=False),
      Column(u'position', INTEGER(display_width=5),
             server_default=None),
      Column('added',
             DateTime(),
             nullable=False,
             default=func.now()),
      schema=None)

Table('user_song_stats',
      metadata,
      Column(u'user_id', INTEGER(display_width=10), ForeignKey(u'users.id'),
             primary_key=True, nullable=False),
      Column(u'song_id', INTEGER(display_width=11), ForeignKey(u'song.id'),
             primary_key=True, nullable=False),
      Column(u'when', DATETIME(), primary_key=True,
             nullable=False), schema=None)

Table('channel_song_data',
      metadata,
      Column(u'channel_id', INTEGER(display_width=10),
             ForeignKey(u'channel.id'),
             primary_key=True, nullable=False),
      Column(u'song_id',
             INTEGER(display_width=10),
             ForeignKey(u'song.id'),
             primary_key=True,
             nullable=False),
      Column(u'played', INTEGER(display_width=10),
             nullable=False,
             server_default=0),
      Column(u'voted',
             INTEGER(display_width=10),
             nullable=False,
             server_default=0),
      Column(u'skipped', INTEGER(display_width=10),
             nullable=False,
             server_default=0),
      Column(u'lastPlayed', DATETIME()),
      Column(u'cost', INTEGER(display_width=11),
             server_default=5), schema=None)

Table('song_has_genre',
      metadata,
      Column(u'song_id', INTEGER(display_width=10), ForeignKey(u'song.id'),
             primary_key=True, nullable=False),
      Column(u'genre_id', INTEGER(display_width=10), ForeignKey(u'genre.id'),
             primary_key=True, nullable=False),
      schema=None)

Table('lastfm_queue',
      metadata,
      Column(u'queue_id', INTEGER(display_width=10),
             primary_key=True, nullable=False),
      Column(u'song_id',
             INTEGER(display_width=10),
             ForeignKey(u'song.id'),
             nullable=False),
      Column(u'time_played', DATETIME(), nullable=False),
      Column(u'time_started', DATETIME(),
             nullable=False), schema=None)

Table('song_has_tag',
      metadata,
      Column('song_id', Integer(), ForeignKey('song.id')),
      Column('tag', String(length=32),
             ForeignKey('tag.label')), schema=None)
