
<div style="width: 100%; text-align: center;">
    <img src="/img/jukebox_logo_mobile.png" alt="Wicked Jukebox" />
</div>
<form id="login" method="post" action="<?php echo $this->form->getAction(); ?>" data-ajax="false">
    <div data-role="fieldcontain" class="ui-hide-label">
            <label for="fUsername">
                Username:
            </label>
            <input id="fUsername" name="username" value="" type="text" placeholder="Username" />
    </div>
    <div data-role="fieldcontain" class="ui-hide-label">
        <fieldset data-role="controlgroup">
            <label for="fPassword" class="ui-hidden-accessible">
                Password:
            </label>
            <input id="fPassword" name="password" value="" type="password" placeholder="Password" />
        </fieldset>
    </div>
    <input type="submit" data-theme="c" value="Login" />
</form>
