<p>
<h1>
    <img alt='Wicked Jukebox' src='/img/jukebox_logo_mobile.png'>
</h1>
</p>
<p>
    <br>
<form action='/login' data-ajax='false' id='user-login-form' method='post' rel='external'>
    <fieldset data-role='fieldcontain'>
        <p>
            <input autocapitalize='off' data-role='input' data-theme='b' id='username' name='username' placeholder='username'>
        </p>
        <p>
            <input autocapitalize='off' data-role='input' data-theme='b' id='password' name='password' placeholder='password' type='password'>
        </p>
        <p>
            <input data-role='none' id='remember_me' name='remember_me' type='checkbox' value='true'>
            <label class='wide' for='remember_me'>
                <small>Remember me?</small>
            </label>
        </p>
        <p>
            <button data-theme='a' type='submit'>Login</button>
        </p>
    </fieldset>
</form>
</p>
