<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Twitter Bootstrap</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="/css/bootstrap.css" rel="stylesheet">
    <script src="/js/bootstrap.js"></script>

</head>
<body>




<div class="container">

<div class="row">
    <div class="span12">
        <div class="row">
            <div class="span4">
                User info
            </div>
            <div class="span5">
                <form class="form-search">
                    <input type="text" class="input-xlarge search-query">
                    <button type="submit" class="btn">Search</button>
                </form>
            </div>
            <div class="span3">
                logo
            </div>
        </div>
    </div>
</div>


<?php echo $this->layout()->content; ?>


</div>

</body>
</html>