<!DOCTYPE html>
<html lang="en">
<head>
    <?php
    # Title
    echo $this->headTitle();

    # Meta data
    echo $this->headMeta()
        ->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8')
        ->appendHttpEquiv('Content-Language', 'en-US');

    # CSS
    echo $this->headLink()
        ->appendStylesheet($this->baseUrl() . '/css/bootstrap.css');

    # Javascript
    echo $this->headScript()
        ->appendFile($this->baseUrl() . '/js/bootstrap.js', 'text/javascript');
    ?>
</head>
<body>
<?php echo '<!-- Mode: ' . APPLICATION_ENV . ' mode -->'; ?>
<?php
$auth = Zend_Auth::getInstance();
?>
<div class="container">

<?php if ($auth->hasIdentity()) : ?>
<div class="row">
    <div class="span12">
        <div class="row">
            <div class="span4">
                User info
            </div>
            <div class="span5">
                <form class="form-search">
                    <input type="text" class="input-xlarge search-query">
                    <button type="submit" class="btn">Search</button>
                </form>
            </div>
            <div class="span3">
                logo
            </div>
        </div>
    </div>
</div>
<? endif ?>

    <?php echo $this->partial('priorityMessages.phtml', array('priorityMessages'=>$this->priorityMessenger())); ?>

<?php echo $this->layout()->content; ?>

</div>

</body>
</html>