<?php
    $current = $this->channel['current'];
?>

<div class="currentlyPlaying">

    <h3>Currently playing</h3>

    <div style="float: left;"">
        <img src="/images/album/splash/<?php echo $current['song']['album']['id']; ?>.png" style="border: 1px grey solid; padding: 4px;"/>
    </div>
    <div style="float: left; padding:   10px;">

        <p>
            <strong><?php echo $current['song']['title']; ?></strong><br />
            by <strong><?php echo $current['song']['artist']['name']; ?></strong><br />
            on <strong><?php echo $current['song']['album']['name']; ?></strong><br />
            <?php echo $current['song']['duration']; ?>
        </p>

    </div>

</div>

<hr style="clear: both; border: 0" />
    <p>&nbsp;</p>

			<div class="content-primary">
                <ul data-role="listview">
                    <li data-role="list-divider">Queue</li>
                    <?php if (count($this->queue) > 0) : ?>
                    <?php foreach ($this->queue as $q) : ?>
        <li><a href="index.html"><?php echo $q->getSong()->getArtist()->getName() ?> - <?php echo $q->getSong()->getTitle() ?></a></li>
        <?php endforeach ?>
                    <?php else :  ?>
    <li>the queue is empty</li>
                    <?php endif ?>
                </ul>
            </div>
