<?php
    $current = $this->channel['current'];
?>
			<div class="content-primary">
                <ul data-role="listview">
                    <li data-role="list-divider">Currently playing</li>
                    <li><a href="/mobile/song/detail/id/<?php echo $current['song']['id']; ?>/">
                        <img src="/images/album/list/<?php echo $current['song']['album']['id']; ?>.png" />
                        <h3><?php echo $current['song']['title']; ?> (<?php echo $this->jukeboxTime($current['song']['duration']); ?>)</h3>
                        <p>by <strong><?php echo $current['song']['artist']['name']; ?></strong></p>
                        <p>on <strong><?php echo $current['song']['album']['name']; ?></strong> (<?php echo date('Y', $current['song']['album']['release_date']) ?>)</p>
                    </a></li>

                    <li data-role="list-divider">Queue <?php if (count($this->queue) > 0) : ?>(<?php echo count($this->queue) ?> items)<?php endif ?></li>
                    <?php if (count($this->queue) > 0) : ?>
                    <?php foreach ($this->queue as $q) : ?>
        <li>
            <a href="/mobile/song/detail/id/<?php echo $q->getSong()->getId(); ?>/">
                <img src="/images/album/list/<?php echo $q->getSong()->getAlbum()->getId(); ?>.png" />
                <h3><?php echo $q->getSong()->getTitle() ?> (<?php echo $this->jukeboxTime($q->getSong()->getDuration()) ?>)</h3>
                <p><?php echo $q->getSong()->getArtist()->getName() ?></p>
            </a>
        </li>
        <?php endforeach ?>
                    <?php else :  ?>
    <li>the queue is empty</li>
                    <?php endif ?>
                </ul>
            </div>
