# type: ignore
# pylint: skip-file
"""
baseline (django-reconciled schema)

Revision ID: 94d889ec82de
Revises: None
Create Date: 2026-07-12 14:09:12.459984

"""

# revision identifiers, used by Alembic.
revision = "94d889ec82de"
down_revision = None

from textwrap import dedent

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=50), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("country", sa.String(length=16), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("website", sa.String(length=255), nullable=True),
        sa.Column("wikipage", sa.String(length=255), nullable=True),
        sa.Column("mbid", sa.String(length=32), nullable=True),
        sa.Column("lastfm_url", sa.String(length=255), nullable=True),
        sa.Column("founded_year", sa.SmallInteger(), nullable=True),
        sa.Column("added", sa.DateTime(), nullable=True),
        sa.Column("photo", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("slug", name="uq_artist_slug"),
    )
    op.create_table(
        "auth_group",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "auth_user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("password", sa.String(length=128), nullable=False),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("username", sa.String(length=150), nullable=False),
        sa.Column("first_name", sa.String(length=150), nullable=False),
        sa.Column("last_name", sa.String(length=150), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("is_staff", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("date_joined", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "channel",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column(
            "public", sa.Boolean(), server_default=sa.text("1"), nullable=False
        ),
        sa.Column("backend", sa.String(length=64), nullable=False),
        sa.Column("backend_params", sa.Text(), nullable=True),
        sa.Column("ping", sa.DateTime(), nullable=True),
        sa.Column(
            "active", sa.Boolean(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("status", sa.Integer(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("mood_low", sa.SmallInteger(), nullable=True),
        sa.Column("mood_high", sa.SmallInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "channel_album_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.Column("album_id", sa.Integer(), nullable=False),
        sa.Column(
            "played", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "channel_id_2",
        "channel_album_data",
        ["channel_id", "album_id"],
        unique=True,
    )
    op.create_table(
        "collection",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "collection_has_song",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("collection_id", sa.Integer(), nullable=False),
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column("last_played", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "collection_id",
        "collection_has_song",
        ["collection_id", "song_id"],
        unique=True,
    )
    op.create_table(
        "country",
        sa.Column(
            "country_code",
            sa.String(length=16),
            server_default=sa.text("''"),
            nullable=False,
        ),
        sa.Column(
            "country_name",
            sa.String(length=100),
            server_default=sa.text("''"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("country_code"),
    )
    op.create_table(
        "django_celery_results_chordcounter",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.String(length=255), nullable=False),
        sa.Column("sub_tasks", sa.Text(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("group_id"),
    )
    op.create_table(
        "django_celery_results_groupresult",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.String(length=255), nullable=False),
        sa.Column("date_created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("date_done", sa.DateTime(timezone=True), nullable=False),
        sa.Column("content_type", sa.String(length=128), nullable=False),
        sa.Column("content_encoding", sa.String(length=64), nullable=False),
        sa.Column("result", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("group_id"),
    )
    op.create_index(
        "django_cele_date_cr_bd6c1d_idx",
        "django_celery_results_groupresult",
        ["date_created"],
        unique=False,
    )
    op.create_index(
        "django_cele_date_do_caae0e_idx",
        "django_celery_results_groupresult",
        ["date_done"],
        unique=False,
    )
    op.create_table(
        "django_celery_results_taskresult",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("content_type", sa.String(length=128), nullable=False),
        sa.Column("content_encoding", sa.String(length=64), nullable=False),
        sa.Column("result", sa.Text(), nullable=True),
        sa.Column("date_done", sa.DateTime(timezone=True), nullable=False),
        sa.Column("traceback", sa.Text(), nullable=True),
        sa.Column("meta", sa.Text(), nullable=True),
        sa.Column("task_args", sa.Text(), nullable=True),
        sa.Column("task_kwargs", sa.Text(), nullable=True),
        sa.Column("task_name", sa.String(length=255), nullable=True),
        sa.Column("worker", sa.String(length=100), nullable=True),
        sa.Column("date_created", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("task_id"),
    )
    op.create_index(
        "django_cele_date_cr_f04a50_idx",
        "django_celery_results_taskresult",
        ["date_created"],
        unique=False,
    )
    op.create_index(
        "django_cele_date_do_f59aad_idx",
        "django_celery_results_taskresult",
        ["date_done"],
        unique=False,
    )
    op.create_index(
        "django_cele_status_9b6201_idx",
        "django_celery_results_taskresult",
        ["status"],
        unique=False,
    )
    op.create_index(
        "django_cele_task_na_08aec9_idx",
        "django_celery_results_taskresult",
        ["task_name"],
        unique=False,
    )
    op.create_index(
        "django_cele_worker_d54dd8_idx",
        "django_celery_results_taskresult",
        ["worker"],
        unique=False,
    )
    op.create_table(
        "django_content_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("app_label", sa.String(length=100), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "django_content_type_app_label_model_76bd3d3b_uniq",
        "django_content_type",
        ["app_label", "model"],
        unique=True,
    )
    op.create_table(
        "django_migrations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("app", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("applied", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "django_session",
        sa.Column("session_key", sa.String(length=40), nullable=False),
        sa.Column("session_data", sa.Text(), nullable=False),
        sa.Column("expire_date", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("session_key"),
    )
    op.create_index(
        "django_session_expire_date_a5c62663",
        "django_session",
        ["expire_date"],
        unique=False,
    )
    op.create_table(
        "dynamicPlaylist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=True),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column(
            "probability",
            sa.Float(),
            nullable=False,
            comment="Probability at which a song is picked from the playlisy (0.0-1.0)",
        ),
        sa.Column("label", sa.String(length=64), nullable=True),
        sa.Column("query", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=50), nullable=True),
        sa.Column("startdate", sa.DateTime(), nullable=False),
        sa.Column("enddate", sa.DateTime(), nullable=False),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lon", sa.Float(), nullable=True),
        sa.Column("photo", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug", name="uq_events_slug"),
    )
    op.create_index(
        "startdate", "events", ["startdate", "enddate"], unique=False
    )
    op.create_table(
        "genre",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("slug", sa.String(length=50), nullable=True),
        sa.Column("added", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("slug", name="uq_genre_slug"),
    )
    op.create_table(
        "groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=32), nullable=False),
        sa.Column(
            "admin", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "nocredits",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "queue_skip",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "queue_remove",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "queue_add",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "log",
        sa.Column("priority", sa.String(length=32), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "date",
            sa.DateTime(timezone=True),
            server_default=sa.text(
                "current_timestamp() ON UPDATE current_timestamp()"
            ),
            nullable=False,
        ),
    )
    op.create_table(
        "playlist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("slug", sa.String(length=50), nullable=True),
        sa.Column("probability", sa.Float(), nullable=True),
        sa.Column(
            "public", sa.Boolean(), server_default=sa.text("0"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug", name="uq_playlist_slug"),
    )
    op.create_index(
        "user_id", "playlist", ["user_id", "probability"], unique=False
    )
    op.create_table(
        "playlist_has_song",
        sa.Column("playlist_id", sa.Integer(), nullable=False),
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column("added", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("playlist_id", "song_id"),
    )
    op.create_table(
        "randomSongsToUse",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "used", sa.Boolean(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("in_string", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("used", "randomSongsToUse", ["used"], unique=False)
    op.create_table(
        "render_presets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("preset", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("hmax", sa.Integer(), nullable=False),
        sa.Column("wmax", sa.Integer(), nullable=False),
        sa.Column("placeholder", sa.String(length=64), nullable=True),
        sa.Column("noproportion", sa.Boolean(), nullable=True),
        sa.Column(
            "force_mime",
            sa.Enum("JPEG", "GIF", "PNG", name="imageenum"),
            nullable=True,
        ),
        sa.Column(
            "crop",
            sa.String(length=8),
            server_default=sa.text("'center'"),
            nullable=False,
        ),
        sa.Column("placeholder_image", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "category", "render_presets", ["category", "preset"], unique=False
    )
    op.create_table(
        "setting_text",
        sa.Column("var", sa.String(length=32), nullable=False),
        sa.Column("text_en", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("var"),
    )
    op.create_table(
        "state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=64), nullable=False),
        sa.Column("value", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("channel_id", "state", ["channel_id", "state"], unique=True)
    op.create_table(
        "tag",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=32), nullable=False),
        sa.Column(
            "inserted",
            sa.DateTime(timezone=True),
            server_default=sa.text("current_timestamp()"),
            nullable=False,
        ),
        sa.Column(
            "modified",
            sa.DateTime(timezone=True),
            server_default=sa.text("'0000-00-00 00:00:00'"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("label"),
    )
    op.create_table(
        "thumbnail_kvstore",
        sa.Column("key", sa.String(length=200), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "album",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=50), nullable=True),
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column(
            "disc_no",
            sa.SmallInteger(),
            server_default=sa.text("1"),
            nullable=False,
        ),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.Column("added", sa.DateTime(), nullable=False),
        sa.Column(
            "downloaded",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "type",
            sa.String(length=32),
            server_default=sa.text("'album'"),
            nullable=True,
        ),
        sa.Column("path", sa.String(length=255), nullable=False),
        sa.Column("coverart", sa.String(length=255), nullable=True),
        sa.Column("mbid", sa.String(length=32), nullable=True),
        sa.Column("lastfm_url", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["artist_id"], ["artist.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("path"),
        sa.UniqueConstraint("slug", name="uq_album_slug"),
    )
    op.create_index("artist_id", "album", ["artist_id"], unique=False)
    op.create_table(
        "auth_permission",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("content_type_id", sa.Integer(), nullable=False),
        sa.Column("codename", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_type_id"],
            ["django_content_type.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "auth_permission_content_type_id_codename_01ab375a_uniq",
        "auth_permission",
        ["content_type_id", "codename"],
        unique=True,
    )
    op.create_table(
        "auth_user_groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["auth_group.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "auth_user_groups_group_id_97559544_fk_auth_group_id",
        "auth_user_groups",
        ["group_id"],
        unique=False,
    )
    op.create_index(
        "auth_user_groups_user_id_group_id_94350c0c_uniq",
        "auth_user_groups",
        ["user_id", "group_id"],
        unique=True,
    )
    op.create_table(
        "django_admin_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("action_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("object_id", sa.Text(), nullable=True),
        sa.Column("object_repr", sa.String(length=200), nullable=False),
        sa.Column("action_flag", sa.Integer(), nullable=False),
        sa.Column("change_message", sa.Text(), nullable=False),
        sa.Column("content_type_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_type_id"],
            ["django_content_type.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "django_admin_log_content_type_id_c4bce8eb_fk_django_co",
        "django_admin_log",
        ["content_type_id"],
        unique=False,
    )
    op.create_index(
        "django_admin_log_user_id_c564eba6_fk_auth_user_id",
        "django_admin_log",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "rest_framework_tracking_apirequestlog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("response_ms", sa.Integer(), nullable=False),
        sa.Column("path", sa.String(length=200), nullable=False),
        sa.Column("remote_addr", sa.String(length=39), nullable=False),
        sa.Column("host", sa.String(length=200), nullable=False),
        sa.Column("method", sa.String(length=10), nullable=False),
        sa.Column("query_params", sa.Text(), nullable=True),
        sa.Column("data", sa.Text(), nullable=True),
        sa.Column("response", sa.Text(), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("view", sa.String(length=200), nullable=True),
        sa.Column("view_method", sa.String(length=200), nullable=True),
        sa.Column("errors", sa.Text(), nullable=True),
        sa.Column("username_persistent", sa.String(length=200), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth_user.id"],
            name="rest_framework_track_user_id_671b70b7_fk_auth_user",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "rest_framework_track_user_id_671b70b7_fk_auth_user",
        "rest_framework_tracking_apirequestlog",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "rest_framework_tracking_apirequestlog_path_fe81f91b",
        "rest_framework_tracking_apirequestlog",
        ["path"],
        unique=False,
    )
    op.create_index(
        "rest_framework_tracking_apirequestlog_requested_at_b6f1c2f2",
        "rest_framework_tracking_apirequestlog",
        ["requested_at"],
        unique=False,
    )
    op.create_index(
        "rest_framework_tracking_apirequestlog_status_code_3c9e2003",
        "rest_framework_tracking_apirequestlog",
        ["status_code"],
        unique=False,
    )
    op.create_index(
        "rest_framework_tracking_apirequestlog_view_5bd1e407",
        "rest_framework_tracking_apirequestlog",
        ["view"],
        unique=False,
    )
    op.create_index(
        "rest_framework_tracking_apirequestlog_view_method_dd790881",
        "rest_framework_tracking_apirequestlog",
        ["view_method"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=32), nullable=False),
        sa.Column("cookie", sa.String(length=32), nullable=False),
        sa.Column("password", sa.String(length=32), nullable=False),
        sa.Column("fullname", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=128), nullable=False),
        sa.Column("credits", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column(
            "downloads",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "votes", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "skips", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "selects", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("added", sa.DateTime(), nullable=False),
        sa.Column("proof_of_life", sa.DateTime(), nullable=False),
        sa.Column("proof_of_listening", sa.DateTime(), nullable=True),
        sa.Column("IP", sa.String(length=32), nullable=False),
        sa.Column("picture", sa.String(length=255), nullable=False),
        sa.Column("lifetime", sa.BigInteger(), nullable=False),
        sa.Column(
            "channel_id",
            sa.Integer(),
            server_default=sa.text("1"),
            nullable=False,
        ),
        sa.Column("pinnedIp", sa.String(length=32), nullable=True),
        sa.Column("django_user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
            name="users_ibfk_1",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("cookie", "users", ["cookie"], unique=True)
    op.create_index(
        "django_user_id_idx", "users", ["django_user_id"], unique=True
    )
    op.create_index("group_id", "users", ["group_id"], unique=False)
    op.create_index("username", "users", ["username"], unique=True)
    op.create_table(
        "auth_group_permissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("permission_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["auth_group.id"],
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["auth_permission.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "auth_group_permissions_group_id_permission_id_0cd325b0_uniq",
        "auth_group_permissions",
        ["group_id", "permission_id"],
        unique=True,
    )
    op.create_table(
        "auth_user_user_permissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("permission_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["auth_permission.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm",
        "auth_user_user_permissions",
        ["permission_id"],
        unique=False,
    )
    op.create_index(
        "auth_user_user_permissions_user_id_permission_id_14a6b632_uniq",
        "auth_user_user_permissions",
        ["user_id", "permission_id"],
        unique=True,
    )
    op.create_table(
        "setting",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("var", sa.String(length=32), nullable=False),
        sa.Column("value", mysql.LONGTEXT(), nullable=True),
        sa.Column(
            "channel_id",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "user_id", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["channel.id"],
            name="setting_ibfk_2",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="setting_ibfk_1",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("channel_id", "setting", ["channel_id"], unique=False)
    op.create_index("user_id", "setting", ["user_id"], unique=False)
    op.create_index(
        "var_2", "setting", ["var", "channel_id", "user_id"], unique=True
    )
    op.create_table(
        "shoutbox",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("message", sa.String(length=255), nullable=False),
        sa.Column("added", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="shoutbox_ibfk_1",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("user_id", "shoutbox", ["user_id"], unique=False)
    op.create_index("when", "shoutbox", ["added"], unique=False)
    op.create_table(
        "song",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=50), nullable=True),
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.Column("album_id", sa.Integer(), nullable=True),
        sa.Column("intro_id", sa.Integer(), nullable=True),
        sa.Column("track_no", sa.Integer(), nullable=True),
        sa.Column(
            "disc_no",
            sa.SmallInteger(),
            server_default=sa.text("1"),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("duration", sa.Float(asdecimal=True), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("localpath", sa.String(length=255), nullable=False),
        sa.Column(
            "downloaded",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=True,
        ),
        sa.Column("lastScanned", sa.DateTime(), nullable=True),
        sa.Column("bitrate", sa.Integer(), nullable=True),
        sa.Column("filesize", sa.Integer(), nullable=True),
        sa.Column("checksum", sa.String(length=64), nullable=True),
        sa.Column("lyrics", sa.Text(), nullable=True),
        sa.Column(
            "lyrics_synced",
            sa.Text(),
            server_default=sa.text("''"),
            nullable=False,
        ),
        sa.Column("waveform", sa.Text(), nullable=True),
        sa.Column(
            "broken", sa.Boolean(), server_default=sa.text("0"), nullable=True
        ),
        sa.Column(
            "exclude_from_random",
            sa.Boolean(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "dirty", sa.Boolean(), server_default=sa.text("0"), nullable=True
        ),
        sa.Column("added", sa.DateTime(), nullable=False),
        sa.Column(
            "available",
            sa.Boolean(),
            server_default=sa.text("1"),
            nullable=True,
        ),
        sa.Column("coverart", sa.String(length=255), nullable=True),
        sa.Column("bpm", sa.SmallInteger(), nullable=True),
        sa.Column("musical_key", sa.String(length=8), nullable=True),
        sa.Column("loudness", sa.Float(), nullable=True),
        sa.Column("true_peak", sa.Float(), nullable=True),
        sa.Column("crest_factor", sa.Float(), nullable=True),
        sa.Column("replaygain_written", sa.DateTime(), nullable=True),
        sa.Column("mood_score", sa.SmallInteger(), nullable=True),
        sa.Column("asin", sa.String(length=32), nullable=True),
        sa.Column("acoustid_id", sa.String(length=32), nullable=True),
        sa.Column(
            "acoustid_fingerprint",
            sa.Text(),
            server_default=sa.text("''"),
            nullable=False,
        ),
        sa.Column("mbid", sa.String(length=32), nullable=True),
        sa.Column("lastfm_url", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["album_id"],
            ["album.id"],
            name="song_ibfk_2",
            onupdate="CASCADE",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artist.id"],
            name="song_ibfk_1",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("intro_id", name="uq_song_intro_id"),
        sa.UniqueConstraint("localpath"),
        sa.UniqueConstraint("slug", name="uq_song_slug"),
    )
    op.create_index("album_id", "song", ["album_id"], unique=False)
    op.create_index("artist_id", "song", ["artist_id"], unique=False)
    op.create_index(
        "song_avail_broken_idx", "song", ["available", "broken"], unique=False
    )
    op.create_index("song_mood_score_idx", "song", ["mood_score"], unique=False)
    op.create_table(
        "user_album_stats",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("album_id", sa.Integer(), nullable=False),
        sa.Column("when", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["album_id"],
            ["album.id"],
            name="user_album_stats_ibfk_2",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="user_album_stats_ibfk_1",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
    )
    op.create_index("album_id", "user_album_stats", ["album_id"], unique=False)
    op.create_index("user_id", "user_album_stats", ["user_id"], unique=False)
    op.create_table(
        "channel_song_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.Column(
            "played", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "voted", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "skipped", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("lastPlayed", sa.DateTime(), nullable=True),
        sa.Column(
            "cost", sa.Integer(), server_default=sa.text("5"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["channel.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["song_id"], ["song.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "channel_id_2",
        "channel_song_data",
        ["channel_id", "song_id"],
        unique=True,
    )
    op.create_index("song_id", "channel_song_data", ["song_id"], unique=False)
    op.create_table(
        "lastfm_queue",
        sa.Column("queue_id", sa.Integer(), nullable=False),
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.Column("time_played", sa.DateTime(), nullable=False),
        sa.Column("time_started", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["song_id"],
            ["song.id"],
            name="lastfm_queue_ibfk_2",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("queue_id"),
    )
    op.create_index("song_id", "lastfm_queue", ["song_id"], unique=False)
    op.create_table(
        "queue",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.Column(
            "position", sa.Integer(), server_default=sa.text("0"), nullable=True
        ),
        sa.Column("added", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["channel.id"],
            name="queue_ibfk_3",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["song_id"],
            ["song.id"],
            name="queue_ibfk_2",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="queue_ibfk_1",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("channel_id", "queue", ["channel_id"], unique=False)
    op.create_index("song_id", "queue", ["song_id"], unique=False)
    op.create_index("user_id", "queue", ["user_id"], unique=False)
    op.create_table(
        "song_has_genre",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.Column("genre_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["genre_id"],
            ["genre.id"],
            name="song_has_genre_ibfk_1",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["song_id"],
            ["song.id"],
            name="song_has_genre_ibfk_2",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("genre_id", "song_has_genre", ["song_id"], unique=False)
    op.create_index("song_id", "song_has_genre", ["genre_id"], unique=False)
    op.create_index(
        "song_id_2", "song_has_genre", ["song_id", "genre_id"], unique=True
    )
    op.create_table(
        "song_has_tag",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["song_id"],
            ["song.id"],
            name="song_has_tag_song_id",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tag.id"],
            name="song_has_tag_tag_id",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "song_id", "song_has_tag", ["song_id", "tag_id"], unique=True
    )
    op.create_table(
        "user_song_standing",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.Column(
            "standing",
            sa.Enum("LOVE", "HATE", name="standingenum"),
            nullable=False,
        ),
        sa.Column(
            "inserted",
            sa.DateTime(timezone=True),
            server_default=sa.text("current_timestamp()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["song_id"],
            ["song.id"],
            name="user_song_standing_song_id",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="user_song_standing_user_id",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "user_song_id",
        "user_song_standing",
        ["user_id", "song_id"],
        unique=True,
    )
    op.create_table(
        "user_song_stats",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.Column("when", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["song_id"],
            ["song.id"],
            name="user_song_stats_ibfk_2",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="user_song_stats_ibfk_1",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "song_id", "when"),
    )
    op.create_index("song_id", "user_song_stats", ["song_id"], unique=False)
    op.create_index("user_id", "user_song_stats", ["user_id"], unique=False)
    # ### end Alembic commands ###

    # `history` is a plain SQL VIEW, not part of Base.metadata, so
    # autogenerate cannot see or emit it. Recreated verbatim (same
    # definition as the old initial-stamp migration) so the squash
    # preserves it.
    op.execute(dedent("""\
        CREATE VIEW `history` AS
        select
            `s`.`id` AS `song_id`,
            `rel`.`channel_id` AS `channel`,
            concat(`a`.`name`,_utf8' - ',`s`.`title`) AS `track`,
            `rel`.`lastPlayed` AS `time`
        from (
            (
                `channel_song_data` `rel`
                join `song` `s` on (`s`.`id` = `rel`.`song_id`)
            )
            join `artist` `a` on (`a`.`id` = `s`.`artist_id`)
        )
        order by `rel`.`lastPlayed` desc ;
        """))


def downgrade():
    op.execute("DROP VIEW IF EXISTS `history`")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("user_id", table_name="user_song_stats")
    op.drop_index("song_id", table_name="user_song_stats")
    op.drop_table("user_song_stats")
    op.drop_index("user_song_id", table_name="user_song_standing")
    op.drop_table("user_song_standing")
    op.drop_index("song_id", table_name="song_has_tag")
    op.drop_table("song_has_tag")
    op.drop_index("song_id_2", table_name="song_has_genre")
    op.drop_index("song_id", table_name="song_has_genre")
    op.drop_index("genre_id", table_name="song_has_genre")
    op.drop_table("song_has_genre")
    op.drop_index("user_id", table_name="queue")
    op.drop_index("song_id", table_name="queue")
    op.drop_index("channel_id", table_name="queue")
    op.drop_table("queue")
    op.drop_index("song_id", table_name="lastfm_queue")
    op.drop_table("lastfm_queue")
    op.drop_index("song_id", table_name="channel_song_data")
    op.drop_index("channel_id_2", table_name="channel_song_data")
    op.drop_table("channel_song_data")
    op.drop_index("user_id", table_name="user_album_stats")
    op.drop_index("album_id", table_name="user_album_stats")
    op.drop_table("user_album_stats")
    op.drop_index("song_mood_score_idx", table_name="song")
    op.drop_index("song_avail_broken_idx", table_name="song")
    op.drop_index("artist_id", table_name="song")
    op.drop_index("album_id", table_name="song")
    op.drop_table("song")
    op.drop_index("when", table_name="shoutbox")
    op.drop_index("user_id", table_name="shoutbox")
    op.drop_table("shoutbox")
    op.drop_index("var_2", table_name="setting")
    op.drop_index("user_id", table_name="setting")
    op.drop_index("channel_id", table_name="setting")
    op.drop_table("setting")
    op.drop_index(
        "auth_user_user_permissions_user_id_permission_id_14a6b632_uniq",
        table_name="auth_user_user_permissions",
    )
    op.drop_index(
        "auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm",
        table_name="auth_user_user_permissions",
    )
    op.drop_table("auth_user_user_permissions")
    op.drop_index(
        "auth_group_permissions_group_id_permission_id_0cd325b0_uniq",
        table_name="auth_group_permissions",
    )
    op.drop_table("auth_group_permissions")
    op.drop_index("username", table_name="users")
    op.drop_index("group_id", table_name="users")
    op.drop_index("django_user_id_idx", table_name="users")
    op.drop_index("cookie", table_name="users")
    op.drop_table("users")
    op.drop_index(
        "rest_framework_tracking_apirequestlog_view_method_dd790881",
        table_name="rest_framework_tracking_apirequestlog",
    )
    op.drop_index(
        "rest_framework_tracking_apirequestlog_view_5bd1e407",
        table_name="rest_framework_tracking_apirequestlog",
    )
    op.drop_index(
        "rest_framework_tracking_apirequestlog_status_code_3c9e2003",
        table_name="rest_framework_tracking_apirequestlog",
    )
    op.drop_index(
        "rest_framework_tracking_apirequestlog_requested_at_b6f1c2f2",
        table_name="rest_framework_tracking_apirequestlog",
    )
    op.drop_index(
        "rest_framework_tracking_apirequestlog_path_fe81f91b",
        table_name="rest_framework_tracking_apirequestlog",
    )
    op.drop_index(
        "rest_framework_track_user_id_671b70b7_fk_auth_user",
        table_name="rest_framework_tracking_apirequestlog",
    )
    op.drop_table("rest_framework_tracking_apirequestlog")
    op.drop_index(
        "django_admin_log_user_id_c564eba6_fk_auth_user_id",
        table_name="django_admin_log",
    )
    op.drop_index(
        "django_admin_log_content_type_id_c4bce8eb_fk_django_co",
        table_name="django_admin_log",
    )
    op.drop_table("django_admin_log")
    op.drop_index(
        "auth_user_groups_user_id_group_id_94350c0c_uniq",
        table_name="auth_user_groups",
    )
    op.drop_index(
        "auth_user_groups_group_id_97559544_fk_auth_group_id",
        table_name="auth_user_groups",
    )
    op.drop_table("auth_user_groups")
    op.drop_index(
        "auth_permission_content_type_id_codename_01ab375a_uniq",
        table_name="auth_permission",
    )
    op.drop_table("auth_permission")
    op.drop_index("artist_id", table_name="album")
    op.drop_table("album")
    op.drop_table("thumbnail_kvstore")
    op.drop_table("tag")
    op.drop_index("channel_id", table_name="state")
    op.drop_table("state")
    op.drop_table("setting_text")
    op.drop_index("category", table_name="render_presets")
    op.drop_table("render_presets")
    op.drop_index("used", table_name="randomSongsToUse")
    op.drop_table("randomSongsToUse")
    op.drop_table("playlist_has_song")
    op.drop_index("user_id", table_name="playlist")
    op.drop_table("playlist")
    op.drop_table("log")
    op.drop_table("groups")
    op.drop_table("genre")
    op.drop_index("startdate", table_name="events")
    op.drop_table("events")
    op.drop_table("dynamicPlaylist")
    op.drop_index(
        "django_session_expire_date_a5c62663", table_name="django_session"
    )
    op.drop_table("django_session")
    op.drop_table("django_migrations")
    op.drop_index(
        "django_content_type_app_label_model_76bd3d3b_uniq",
        table_name="django_content_type",
    )
    op.drop_table("django_content_type")
    op.drop_index(
        "django_cele_worker_d54dd8_idx",
        table_name="django_celery_results_taskresult",
    )
    op.drop_index(
        "django_cele_task_na_08aec9_idx",
        table_name="django_celery_results_taskresult",
    )
    op.drop_index(
        "django_cele_status_9b6201_idx",
        table_name="django_celery_results_taskresult",
    )
    op.drop_index(
        "django_cele_date_do_f59aad_idx",
        table_name="django_celery_results_taskresult",
    )
    op.drop_index(
        "django_cele_date_cr_f04a50_idx",
        table_name="django_celery_results_taskresult",
    )
    op.drop_table("django_celery_results_taskresult")
    op.drop_index(
        "django_cele_date_do_caae0e_idx",
        table_name="django_celery_results_groupresult",
    )
    op.drop_index(
        "django_cele_date_cr_bd6c1d_idx",
        table_name="django_celery_results_groupresult",
    )
    op.drop_table("django_celery_results_groupresult")
    op.drop_table("django_celery_results_chordcounter")
    op.drop_table("country")
    op.drop_index("collection_id", table_name="collection_has_song")
    op.drop_table("collection_has_song")
    op.drop_table("collection")
    op.drop_index("channel_id_2", table_name="channel_album_data")
    op.drop_table("channel_album_data")
    op.drop_table("channel")
    op.drop_table("auth_user")
    op.drop_table("auth_group")
    op.drop_table("artist")
    # ### end Alembic commands ###
