<?php

/**
 *
 *
 * @version $Id$
 * @copyright 2006
 */



  $album = Album::getById($_GET['param']);
  $songs = Album::getSongs($_GET['param']);
  $artist = Artist::getById($songs[0]['artist_id']);

  $file_zip = sprintf("%s - %s.zip", $artist['name'], $album['title']);
  $file_zip = str_replace(" ", "_", $file_zip);

  $file_lyrics = sprintf("%s - %s.txt", $artist['name'], $album['title']);
  $file_lyrics = str_replace(" ", "_", $file_lyrics);

  $cover = Album::hasCover($_GET['param']);

  $full_path = sprintf("%s/%s", $temp_path, $file_zip);
  $lyrics_path = sprintf("%s/%s", $temp_path, $file_lyrics);

  $lyrics = 0;

  if (!file_exists($full_path)) {

    $archive_files = array();
    $lyrics_content = "";

    if (!empty($cover))
      array_push($archive_files, $cover);

    foreach ($songs as $song) {
      if (file_exists($song['localpath'])) {
        if (!empty($song['lyrics'])) {
          $lyrics_content .= sprintf("---------------------------------------------------\n\n  %02d  -  %s\n\n%s\n\n", $song['track_no'], $song['song'], strtolower($song['lyrics']));
          $lyrics++;
        }
        array_push($archive_files, $song['localpath']);
      }

    }

    if ($lyrics > 0)
     if ($handle = fopen($lyrics_path, 'w')) {
         fwrite($handle, sprintf("\n  Lyrics generated by Wicked Jukebox\n\n    Artist: %s\n    Album: %s\n\n\n%s\n---------------------------------------------------\n", $artist['name'], $album['title'], $lyrics_content));
         fclose($handle);
        array_push($archive_files, $lyrics_path);
      }

    require_once "File/Archive.php";
    File_Archive::setOption("zipCompressionLevel", 9);

    File_Archive::extract(
      $archive_files,
      File_Archive::toArchive($full_path, File_Archive::toFiles())
    );

  }

  Album::countDownload($_GET['param']);
  User::countDownload($userinfo['user_id']);

  $mime_type = finfo_file($finfo, $full_path);

  header('Content-type: ' . $mime_type);
  header("Content-length: ".filesize($full_path));
  header('Content-Disposition: attachment; filename="'.$file_zip.'"');

  $fp = fopen($full_path, "r");

  fpassthru($fp);
  fclose($fp);

  finfo_close($finfo);

  exit();

?>