---
name: CI
on: push
jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker image
        uses: docker/build-push-action@v4.1.1
        with:
          push: false
          tags: |
            thewickednet.lu/wickedjukebox:ci-build
  check-container:
    runs-on: ubuntu-latest
    services:
      backend:
        image: thewickednet.lu/wickedjukebox:ci-build
        ports:
          - "8000:8000"
    needs:
      - build-container
    steps:
      - name: Request root-URL
        run: |
          curl http://localhost:8000/
