---
name: Check & Release
on: [push]
jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
      - name: Run pre-commit checks
        run: |
          pre-commit run --all

  unit-tests:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb
        ports:
          - 3306:3306
        env:
          MARIADB_DATABASE: jukebox
          MARIADB_USER: jukebox
          MARIADB_PASSWORD: jukebox
          MARIADB_ROOT_PASSWORD: rootpw

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Configure
        run: |
          mkdir -p .wicked/wickedjukebox
          cp config.ini.dist .wicked/wickedjukebox/config.ini
          cp alembic.ini.dist alembic.ini
          sed -i -e "s#^dsn=.*#dsn=mysql+pymysql://jukebox:jukebox@localhost:3306/jukebox?charset=utf8#" .wicked/wickedjukebox/config.ini
          sed -i -e "s#^sqlalchemy.url.*#sqlalchemy.url = mysql+pymysql://jukebox:jukebox@localhost:3306/jukebox?charset=utf8#" alembic.ini
          alembic upgrade head
      - name: Run unit-tests
        run: pytest --color=yes

  create-release:
    needs:
      - code-quality
      - unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build
        run: python -m build
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'push' &&
            startsWith(github.event.ref, 'refs/tags/v')
        with:
          files:
            dist/*
